### ISSUE TITLE
User management signIn fails due to null verify value

### ISSUE THREAD

**Issue by R-T-Weerasinghe** [OnlineShoppingSystemEAD/OnlineShoppingSystem#41]
![image](https://github.com/user-attachments/assets/28f47ca4-a000-4007-aa08-4bd094469441)

proposed fix -> instead of setting the verified property null at signup, make it **false**

**Comment by JanithRavisanka** [comment]
![image](https://github.com/user-attachments/assets/c1f55dd0-6f89-4e1c-81ee-f66bfedb41aa)

fixed
