### ISSUE TITLE
Duplicate accounts can be created with same email. 

### ISSUE THREAD

**Issue by R-T-Weerasinghe** [OnlineShoppingSystemEAD/OnlineShoppingSystem#42]
in auth/signup, you can create as many accounts as you like with the same email.

Fix asap as this causes other issues as well (for example signIn fails when there are multiple accounts with same email)

**Comment by JanithRavisanka** [comment]
<img width="993" alt="image" src="https://github.com/user-attachments/assets/bb654df8-2e41-457e-aeb6-3e1226cf2f44">

fixed
