### ISSUE TITLE
incorrect id used for fetching in user management service

### ISSUE THREAD

**Issue by R-T-Weerasinghe** [OnlineShoppingSystemEAD/OnlineShoppingSystem#45]
user_id and id are different in the table. Currently the code uses id to fetch from DB instead of user_id.

think it needs to be changed to fetching by user_id

![image](https://github.com/user-attachments/assets/3447dd5d-5446-48d2-8ee2-436c425071c6)

![image](https://github.com/user-attachments/assets/2e3861da-336d-456a-a12d-f93f9f0c3ecf)

**Comment by JanithRavisanka** [comment]
![Screenshot 2024-12-02 at 03 26 03](https://github.com/user-attachments/assets/4fafa43e-0a6c-42cb-a99d-142bbf00ee90)

this bug fixed
